// ─── Placeholder content for every Footer link, High-Ticket tone, FR/EN/IT ───
export const FOOTER_PAGES = {
  "tiktok-influencers": {
    fr: { kicker: "Créateurs TikTok", title: "Trouvez les créateurs TikTok qui vendent vraiment", intro: "TikTok n'est pas qu'une question de vues — c'est un canal d'acquisition à part entière quand vous travaillez avec les bons créateurs. Acquisition Pro vous connecte aux profils qui convertissent réellement, avec des données d'engagement vérifiées avant chaque prise de contact.", bullets: ["Scoring d'engagement réel, pas de faux followers", "Filtrage par niche, audience et taux de conversion estimé", "Mise en relation directe, sans agence intermédiaire"], cta: "Explorer les créateurs TikTok" },
    en: { kicker: "TikTok Creators", title: "Find the TikTok creators who actually sell", intro: "TikTok isn't just about views — it's a full acquisition channel when you work with the right creators. Acquisition Pro connects you to profiles that genuinely convert, with verified engagement data before every outreach.", bullets: ["Real engagement scoring, no fake followers", "Filter by niche, audience, and estimated conversion rate", "Direct connection, no middleman agency"], cta: "Explore TikTok creators" },
    it: { kicker: "Creator TikTok", title: "Trova i creator TikTok che vendono davvero", intro: "TikTok non è solo una questione di visualizzazioni — è un canale di acquisizione a tutti gli effetti se lavori con i creator giusti. Acquisition Pro ti connette a profili che convertono realmente, con dati di engagement verificati prima di ogni contatto.", bullets: ["Scoring di engagement reale, niente follower falsi", "Filtra per nicchia, audience e tasso di conversione stimato", "Collegamento diretto, senza agenzia intermediaria"], cta: "Esplora i creator TikTok" },
  },
  "coaching-elite": {
    fr: { kicker: "Coaching", title: "Le Coaching Elite, pour scaler sans deviner", intro: "Un accès direct à des sessions stratégiques individuelles pensées pour les marques qui veulent accélérer leur acquisition sans perdre des mois à tester à l'aveugle. Chaque session est orientée résultats : votre budget, votre niche, votre plan d'action.", bullets: ["Sessions hebdomadaires en VIP Elite, mensuelles en VIP Pro", "Analyse de vos campagnes en cours et correction de trajectoire", "Accès prioritaire à l'équipe Viral Acquisition"], cta: "Débloquer le Coaching Elite" },
    en: { kicker: "Coaching", title: "Elite Coaching, so you scale without guessing", intro: "Direct access to one-on-one strategy sessions built for brands that want to accelerate acquisition without months of blind testing. Every session is results-driven: your budget, your niche, your action plan.", bullets: ["Weekly sessions on VIP Elite, monthly on VIP Pro", "Live review of your running campaigns with course correction", "Priority access to the Viral Acquisition team"], cta: "Unlock Elite Coaching" },
    it: { kicker: "Coaching", title: "Il Coaching Elite, per scalare senza indovinare", intro: "Accesso diretto a sessioni strategiche individuali pensate per i brand che vogliono accelerare l'acquisizione senza mesi di test alla cieca. Ogni sessione è orientata ai risultati: il tuo budget, la tua nicchia, il tuo piano d'azione.", bullets: ["Sessioni settimanali in VIP Elite, mensili in VIP Pro", "Analisi delle campagne in corso e correzione di rotta", "Accesso prioritario al team Viral Acquisition"], cta: "Sblocca il Coaching Elite" },
  },
  "trouvez-votre-talent": {
    fr: { kicker: "Espace Créateurs", title: "Trouvez votre talent, pas un simple contact", intro: "Notre matchmaking IA ne se contente pas de croiser des mots-clés : il analyse la niche, l'audience réelle et le style de contenu pour vous proposer des créateurs qui correspondent vraiment à votre marque — pas juste à votre budget.", bullets: ["Matching basé sur l'audience réelle, pas les abonnés bruts", "Profils vérifiés et disponibles pour collaboration immédiate", "Zéro DM à froid : le contact se fait via la plateforme"], cta: "Trouver mon talent idéal" },
    en: { kicker: "Creators Hub", title: "Find your talent, not just a contact", intro: "Our AI matchmaking doesn't just cross-reference keywords: it analyzes niche, real audience, and content style to surface creators who actually fit your brand — not just your budget.", bullets: ["Matching based on real audience, not raw follower counts", "Verified profiles, available for immediate collaboration", "Zero cold DMs: outreach happens through the platform"], cta: "Find my ideal talent" },
    it: { kicker: "Area Creator", title: "Trova il tuo talento, non un semplice contatto", intro: "Il nostro matchmaking IA non si limita a incrociare parole chiave: analizza nicchia, audience reale e stile dei contenuti per proporti creator che si adattano davvero al tuo brand — non solo al tuo budget.", bullets: ["Matching basato sull'audience reale, non sui follower grezzi", "Profili verificati e disponibili per collaborazione immediata", "Zero DM a freddo: il contatto avviene tramite la piattaforma"], cta: "Trova il mio talento ideale" },
  },
  "matchmaking-crm": {
    fr: { kicker: "Matchmaking & CRM", title: "Le CRM qui pilote vos collaborations comme une agence", intro: "Centralisez marques, créateurs, pitchs et contrats dans un seul outil. Le Matchmaking CRM d'Acquisition Pro suit chaque relation de la prise de contact à la signature, pour que vous ne perdiez plus jamais le fil d'une négociation.", bullets: ["Suivi des accords validés et des contrats signés en un coup d'œil", "Génération de pitchs et de contrats assistée par IA", "Catalogue de talents prioritaires accessible en permanence"], cta: "Découvrir le Matchmaking CRM" },
    en: { kicker: "Matchmaking & CRM", title: "The CRM that runs your collaborations like an agency", intro: "Centralize brands, creators, pitches, and contracts in one tool. Acquisition Pro's Matchmaking CRM tracks every relationship from first contact to signature, so you never lose track of a negotiation again.", bullets: ["See validated deals and signed contracts at a glance", "AI-assisted pitch and contract generation", "Priority talent catalog always at hand"], cta: "Discover the Matchmaking CRM" },
    it: { kicker: "Matchmaking & CRM", title: "Il CRM che gestisce le tue collaborazioni come un'agenzia", intro: "Centralizza brand, creator, pitch e contratti in un unico strumento. Il Matchmaking CRM di Acquisition Pro segue ogni relazione dal primo contatto alla firma, così non perderai mai più il filo di una trattativa.", bullets: ["Accordi validati e contratti firmati a colpo d'occhio", "Generazione di pitch e contratti assistita dall'IA", "Catalogo talenti prioritari sempre a portata di mano"], cta: "Scopri il Matchmaking CRM" },
  },
  "formation-acquisition": {
    fr: { kicker: "Académie", title: "La Formation Acquisition, pour ne plus improviser", intro: "Plus de 10 heures de formation offerte pour maîtriser le sourcing, le matchmaking et l'analyse concurrentielle — pensée pour les marques qui veulent scaler avec méthode plutôt qu'au feeling.", bullets: ["Modules courts et actionnables, à votre rythme", "Basée sur les stratégies réellement utilisées par nos clients VIP", "Incluse gratuitement dès la création de votre compte"], cta: "Accéder à la Formation" },
    en: { kicker: "Academy", title: "Acquisition Training, so you stop improvising", intro: "Over 10 hours of free training to master sourcing, matchmaking, and competitive analysis — built for brands that want to scale with method, not guesswork.", bullets: ["Short, actionable modules, at your own pace", "Based on strategies actually used by our VIP clients", "Included free from the moment you create your account"], cta: "Access the Training" },
    it: { kicker: "Academy", title: "Il Corso Acquisition, per smettere di improvvisare", intro: "Oltre 10 ore di formazione gratuita per padroneggiare sourcing, matchmaking e analisi competitiva — pensato per i brand che vogliono scalare con metodo, non a sensazione.", bullets: ["Moduli brevi e concreti, al tuo ritmo", "Basato sulle strategie realmente usate dai nostri clienti VIP", "Incluso gratuitamente dalla creazione del tuo account"], cta: "Accedi al Corso" },
  },
  "meilleure-agence": {
    fr: { kicker: "Agence", title: "Pourquoi Viral Acquisition est l'agence de référence", intro: "Contrairement à une agence classique qui facture des honoraires fixes sans garantie de résultat, Viral Acquisition combine logiciel propriétaire et expertise humaine pour piloter vos campagnes d'influence avec une exigence de rentabilité.", bullets: ["Une équipe qui utilise le même outil que celui qu'elle vous vend", "Reporting ROI transparent, campagne par campagne", "Aucun engagement de durée imposé"], cta: "Réserver mon appel stratégique" },
    en: { kicker: "Agency", title: "Why Viral Acquisition is the agency to trust", intro: "Unlike a traditional agency charging flat fees with no guarantee of results, Viral Acquisition combines proprietary software with hands-on expertise to run your influencer campaigns with a strict profitability bar.", bullets: ["A team that uses the very tool it sells you", "Transparent ROI reporting, campaign by campaign", "No imposed minimum commitment"], cta: "Book my strategy call" },
    it: { kicker: "Agenzia", title: "Perché Viral Acquisition è l'agenzia di riferimento", intro: "A differenza di un'agenzia classica che addebita tariffe fisse senza garanzia di risultati, Viral Acquisition combina software proprietario ed expertise umana per gestire le tue campagne di influencer marketing con un rigore assoluto sulla redditività.", bullets: ["Un team che usa lo stesso strumento che ti vende", "Reportistica ROI trasparente, campagna per campagna", "Nessun vincolo di durata imposto"], cta: "Prenota la mia chiamata strategica" },
  },
  "strategie-virale": {
    fr: { kicker: "Stratégie", title: "La Stratégie Virale : hackez ce qui marche déjà", intro: "Plutôt que d'inventer une stratégie créative depuis zéro, disséquez ce qui fonctionne déjà pour les leaders de votre marché et adaptez-le à votre marque. C'est exactement ce que permet l'AdSpy d'Acquisition Pro.", bullets: ["Analyse des hooks, formats et CTA les plus performants", "Veille continue sur 80M+ publicités et profils", "Application directe à vos briefs créateurs"], cta: "Construire ma stratégie virale" },
    en: { kicker: "Strategy", title: "The Viral Strategy: hack what already works", intro: "Instead of inventing a creative strategy from scratch, dissect what's already working for the leaders in your market and adapt it to your brand. That's exactly what Acquisition Pro's AdSpy is built for.", bullets: ["Analysis of the best-performing hooks, formats, and CTAs", "Continuous monitoring across 80M+ ads and profiles", "Direct application to your creator briefs"], cta: "Build my viral strategy" },
    it: { kicker: "Strategia", title: "La Strategia Virale: hacka ciò che funziona già", intro: "Invece di inventare una strategia creativa da zero, seziona ciò che funziona già per i leader del tuo mercato e adattalo al tuo brand. È esattamente ciò per cui è pensato l'AdSpy di Acquisition Pro.", bullets: ["Analisi degli hook, formati e CTA più performanti", "Monitoraggio continuo su 80M+ pubblicità e profili", "Applicazione diretta ai tuoi brief per i creator"], cta: "Costruisci la mia strategia virale" },
  },
  "comment-demarrer": {
    fr: { kicker: "Guide de démarrage", title: "Comment démarrer sur Acquisition Pro", intro: "Créez votre compte gratuitement, explorez l'AdSpy pour repérer ce qui marche dans votre niche, puis lancez votre premier matchmaking avec un créateur. Aucune carte bancaire requise pour commencer.", bullets: ["Étape 1 : créez votre compte et choisissez votre profil (marque ou créateur)", "Étape 2 : explorez l'AdSpy et l'Académie gratuite", "Étape 3 : lancez votre premier matchmaking IA"], cta: "Créer mon compte gratuit" },
    en: { kicker: "Getting Started", title: "How to get started on Acquisition Pro", intro: "Create your account for free, explore AdSpy to spot what's working in your niche, then launch your first matchmaking with a creator. No credit card required to start.", bullets: ["Step 1: create your account and pick your profile (brand or creator)", "Step 2: explore AdSpy and the free Academy", "Step 3: launch your first AI matchmaking"], cta: "Create my free account" },
    it: { kicker: "Come iniziare", title: "Come iniziare su Acquisition Pro", intro: "Crea gratuitamente il tuo account, esplora l'AdSpy per individuare cosa funziona nella tua nicchia, poi avvia il tuo primo matchmaking con un creator. Nessuna carta di credito richiesta per iniziare.", bullets: ["Fase 1: crea il tuo account e scegli il tuo profilo (brand o creator)", "Fase 2: esplora l'AdSpy e l'Academy gratuita", "Fase 3: avvia il tuo primo matchmaking IA"], cta: "Crea il mio account gratuito" },
  },
  "analyse-concurrence": {
    fr: { kicker: "Veille Concurrentielle", title: "L'Analyse de la Concurrence, sans zone d'ombre", intro: "Entrez le nom d'une marque et obtenez sa stratégie complète : publicités actives, créateurs utilisés, engagement estimé et tendances de campagne — de quoi construire votre plan d'action sans deviner.", bullets: ["Fiche complète par marque : campagnes, créateurs, performance", "Alertes sur les nouvelles publicités de vos concurrents suivis", "Export direct vers votre CRM Acquisition Pro"], cta: "Analyser un concurrent" },
    en: { kicker: "Competitive Intelligence", title: "Competitor Analysis, with no blind spots", intro: "Enter a brand name and get its full strategy: active ads, creators used, estimated engagement, and campaign trends — everything you need to build your action plan without guessing.", bullets: ["Full brand profile: campaigns, creators, performance", "Alerts on new ads from the competitors you track", "Direct export to your Acquisition Pro CRM"], cta: "Analyze a competitor" },
    it: { kicker: "Analisi Competitiva", title: "L'Analisi della Concorrenza, senza punti ciechi", intro: "Inserisci il nome di un brand e ottieni la sua strategia completa: pubblicità attive, creator utilizzati, engagement stimato e tendenze di campagna — tutto ciò che serve per costruire il tuo piano d'azione senza indovinare.", bullets: ["Scheda completa per brand: campagne, creator, performance", "Avvisi sulle nuove pubblicità dei concorrenti che segui", "Esportazione diretta verso il tuo CRM Acquisition Pro"], cta: "Analizza un concorrente" },
  },
};

export const FOOTER_PAGE_ROUTES = Object.keys(FOOTER_PAGES);
